// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sxVJ9EkwnRBbXcpJQ6s_0af55EXHH-Y',
    appId: '1:44901635530:android:8456fd3a51fdb5a549eb33',
    messagingSenderId: '44901635530',
    projectId: 'boostsocial-a7720',
    storageBucket: 'boostsocial-a7720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0D_IlYEsI4GVzmOLDpk1xsm5FkGW8bU',
    appId: '1:44901635530:ios:381c36407ac10b9849eb33',
    messagingSenderId: '44901635530',
    projectId: 'boostsocial-a7720',
    storageBucket: 'boostsocial-a7720.firebasestorage.app',
    iosBundleId: 'com.example.ticketScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVEvU045aXHjriO4Z4caV6JJ5htu2ftAw',
    appId: '1:44901635530:web:42bab7d639bdc4ff49eb33',
    messagingSenderId: '44901635530',
    projectId: 'boostsocial-a7720',
    authDomain: 'boostsocial-a7720.firebaseapp.com',
    storageBucket: 'boostsocial-a7720.firebasestorage.app',
  );
}
